name: Update Latest blog posts section
on:
  schedule: # Run workflow automatically
    - cron: 0 10 * * * # Runs every day at 10 AM UTC (12 AM GMT)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update README with RSS content
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://henestrosa.dev/rss.xml"
